In [ ]:
# import numpy as np 

# # 'define 1 d array'
# my_list = [1,2,3,4,5,6] 
# my_list
# my_arr = np.array(my_list)
# my_arr

# # define 2d array 
# # my_arr2 = np.array[[1,2,3],[4,5,6],[7,7,9]]
# # my_arr2

# #ndim dimensions
# my_arr.ndim

# # 'shape'
# my_arr.shape

# # '#size'
# my_arr.size

# # datayype

# my_arr.dtype

dtype('int32')

In [18]:
# import library
import numpy as np 
# creating 1D array
my_list = [1,2,3,4,5,6,7,8,9]
my_list
my_arr = np.array(my_list)
my_arr
my_arr = np.array([1,2,3,4,5,6,7,8,9])
my_arr

# "2D array"
my_list2d = [[1,2,3],[4,5,6],[7,8,9]]
my_arr2d = np.array(my_list2d)
my_arr2d

# 3D array
my_list3d = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
my_arr3d = np.array(my_list3d)
my_arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
# 'detail abt array'
# my_arr3d.ndim
# my_arr2d.shape
# my_arr2d.size
my_arr2d.dtype

dtype('int32')

In [28]:
# Subestting and slicing 
orig_list = [1,2,3,4,5,6,7,8,9]
orig_arr = np.array(orig_list)
orig_arr
# 'slicing'
orig_arr[:3]


array([1, 2, 3])

In [36]:
print(orig_arr)
# assigning new value 
new_arr = orig_arr[:3] 
new_arr

new_arr[:] = 100
new_arr
print(orig_arr)

[100 100 100   4   5   6   7   8   9]
[100 100 100   4   5   6   7   8   9]


In [40]:
orig_list = [1,2,3,4,5,6,7,8,9]
orig_arr = np.array(orig_list)
orig_arr
copy_arr = orig_arr[:3].copy()
copy_arr
orig_arr
print(new_arr.base)
print(copy_arr.base)

[100 100 100   4   5   6   7   8   9]
None


In [90]:
my_list2d = [[1,2,3],[4,5,6],[7,8,9]]
my_arr2d = np.array(my_list2d)
my_arr2d
print(my_arr2d)
# my_arr2d[1][1]
my_arr2d[2,1]
# my_arr2d
my_arr2d[1:,1:]

# my_arr2d[1:,1: ]
# my_arr2d[:2,]
# my_arr2d[1:,:2]
# my_arr2d[:2, :2]
my_arr2d[1]
my_arr2d[1,[0,2]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 6])

In [ ]:
# np.array(my_arr2d,dtype=bool)
my_arr2d.argmax()
my_arr2d

8

<!-- Exercise 1

There are 5 numbers in the data set: (8, 12, 16, 24, 4).

What is the mean?
What will be the sum of deviations of individual data points from their mean?
What is the standard deviation? -->

In [ ]:
import numpy as np
data_set = (8, 12, 16, 24, 4)
data_arr = np.array(data_set)
print(data_arr)

mean_value = np.mean(data_arr)
mean_value

# mode_value = np.mod(data_arr)
# mode_value

# mean = (8+12+16+24+4)/5
# print(mean)

[ 8 12 16 24  4]


12.8

In [114]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
# print(arr[1:])
print(arr[1:5:2])

print(arr[1:5:])


[2 4]
[2 3 4 5]


In [115]:
import numpy as np

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])